receivers:
  otlp:
    protocols: # enable OpenTelemetry HTTP Protocol receiver
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/jaeger: # export received traces to Jaeger
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
